// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(class HomePage extends StatelessWidget {

///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0DrDel56Xgtu8wlMCBNtNjWzjBFzzrfM',
    appId: '1:977378230678:web:11f9adf0c037b9b1f31db7',
    messagingSenderId: '977378230678',
    projectId: 'notes-57353',
    authDomain: 'notes-57353.firebaseapp.com',
    storageBucket: 'notes-57353.firebasestorage.app',
    measurementId: 'G-0YHCEENW5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfacXeIAtMjtUQ4o_-fPhLbUV5opLW2qM',
    appId: '1:977378230678:android:e4b6938a5739c6cff31db7',
    messagingSenderId: '977378230678',
    projectId: 'notes-57353',
    storageBucket: 'notes-57353.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIcUqWaoZK1AqPQb7dhBLVqQ7SxWIxwls',
    appId: '1:977378230678:ios:c4d535a6ab7a9225f31db7',
    messagingSenderId: '977378230678',
    projectId: 'notes-57353',
    storageBucket: 'notes-57353.firebasestorage.app',
    iosClientId: '977378230678-dlvio1rmeumba7gpip0lrk5sic6ptg2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIcUqWaoZK1AqPQb7dhBLVqQ7SxWIxwls',
    appId: '1:977378230678:ios:c4d535a6ab7a9225f31db7',
    messagingSenderId: '977378230678',
    projectId: 'notes-57353',
    storageBucket: 'notes-57353.firebasestorage.app',
    iosClientId: '977378230678-dlvio1rmeumba7gpip0lrk5sic6ptg2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0DrDel56Xgtu8wlMCBNtNjWzjBFzzrfM',
    appId: '1:977378230678:web:884a58bbdf31ff41f31db7',
    messagingSenderId: '977378230678',
    projectId: 'notes-57353',
    authDomain: 'notes-57353.firebaseapp.com',
    storageBucket: 'notes-57353.firebasestorage.app',
    measurementId: 'G-ZJWT82ZFB8',
  );

}